### ISSUE TITLE
Should it be synchronously?

### ISSUE THREAD

**Issue by AdityaGovardhan** [jstevenperry/IBM-Developer#24]
https://github.com/jstevenperry/IBM-Developer/blob/master/Node.js/Course/Unit-3/example3.js#L19

// Read a small file **"synchronously"**

**Comment by jstevenperry** [comment]
No. That is a synchronous read.

**Comment by jstevenperry** [comment]
I meant, yes, it should be synchronously. Thank you for reporting this!
