### ISSUE TITLE
Technical information

### ISSUE THREAD

**Issue by eddo67** [jstevenperry/IBM-Developer#31]
Dear Steven,

I hope you are doing well. I have been working on your Node.js videos and I have a problem in unit 6. I was using the recent version of node&npm (v12.18.2 & v6.14.5) and when I wrote the command npm run load-db my console was stuck in loadData():readableStream.on(open): Opened file: ../data/Grocery_UPC_Database.csv 
I re-checked everything according to your video with no luck. I thought it was a version problem so I changed to versions shown in the video  nodev10.6.0 and npm 6.1.0 but the same happened..... stuck in  loadData():readableStream.on(open): Opened file: ../data/Grocery_UPC_Database.csv  with no opportunity to have the prompt and continue with the instructions. Is there something I did wrong? Or anything missing?

I would appreciate your advice.

Best regards

**Comment by gashndolo** [comment]
Had the same problem, I thought it was stuck at the line you mentioned. But it was simply taking a really long time to stream the entire CSV. Give it a wait, it should take a few minutes.

**Comment by eddo67** [comment]
Thank you for the feedback gashndolo. What I did was start from zero...unistall and install node&npm versions as well node_modules. Suddenly it works! With node v12.18.2 and npm v6.14.5. So. my problem is solved.

Thanks
