### ISSUE TITLE
Unit-5 Example-6

### ISSUE THREAD

**Issue by OmPals** [jstevenperry/IBM-Developer#45]
I've just understood the concept of event-loop from the website. 
The event-loop maintains this order: Timer -> Poll -> Check
And the output itself demonstrates that. 

Output given on your website: 
1530402106144:INFO: MAINLINE: START
1530402106146:INFO: MAINLINE: END
1530402106147:INFO: MAINLINE MICROTASK: Promise.resolve.then
1530402106148:INFO: TIMERS PHASE: START iteration 0: setInterval
1530402106148:INFO: TIMERS PHASE: END iteration 0: setInterval
1530402106149:INFO: POLL PHASE: fs.readdir() callback: Directory contains: 8 files
1530402106149:INFO: POLL PHASE MICROTASK: setInterval.fs.readdir.Promise.resolve.then
1530402106149:INFO: CHECK PHASE: setInterval.setImmediate
1530402106149:INFO: CHECK PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
1530402106151:INFO: TIMERS PHASE: TIMER EXPIRED (from iteration 0): setInterval.setTimeout
1530402106151:INFO: TIMERS PHASE: START iteration 1: setInterval
1530402106151:INFO: TIMERS PHASE: END iteration 1: setInterval
1530402106151:INFO: TIMERS PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
1530402106151:INFO: POLL PHASE: fs.readdir() callback: Directory contains: 8 files
1530402106151:INFO: POLL PHASE MICROTASK: setInterval.fs.readdir.Promise.resolve.then
1530402106151:INFO: CHECK PHASE: setInterval.setImmediate
1530402106151:INFO: CHECK PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
1530402106153:INFO: TIMERS PHASE: TIMER EXPIRED (from iteration 1): setInterval.setTimeout
1530402106153:INFO: TIMERS PHASE: START iteration 2: setInterval
1530402106153:INFO: TIMERS PHASE: Max interval count exceeded. Goodbye.
1530402106153:INFO: TIMERS PHASE: END iteration 2: setInterval
1530402106153:INFO: TIMERS PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then

But then I run it in my machine. 

Output on my machine: 
1608448872276:INFO: MAINLINE: START
1608448872284:INFO: MAINLINE: END
1608448872297:INFO: MAINLINE MICROTASK: Promise.resolve.then
1608448872300:INFO: TIMERS PHASE: START iteration 0: setInterval
1608448872302:INFO: TIMERS PHASE: END iteration 0: setInterval
1608448872303:INFO: CHECK PHASE: setInterval.setImmediate
1608448872303:INFO: CHECK PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
1608448872304:INFO: TIMERS PHASE: TIMER EXPIRED (from iteration 0): setInterval.setTimeout
1608448872305:INFO: TIMERS PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
1608448872305:INFO: TIMERS PHASE: START iteration 1: setInterval
1608448872306:INFO: TIMERS PHASE: END iteration 1: setInterval
1608448872308:INFO: POLL PHASE: fs.readdir() callback: Directory contains: 8 files
1608448872308:INFO: POLL PHASE MICROTASK: setInterval.fs.readdir.Promise.resolve.then
1608448872309:INFO: POLL PHASE: fs.readdir() callback: Directory contains: 8 files
1608448872310:INFO: POLL PHASE MICROTASK: setInterval.fs.readdir.Promise.resolve.then
1608448872310:INFO: CHECK PHASE: setInterval.setImmediate
1608448872311:INFO: CHECK PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
1608448872311:INFO: TIMERS PHASE: TIMER EXPIRED (from iteration 1): setInterval.setTimeout
1608448872312:INFO: TIMERS PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
1608448872312:INFO: TIMERS PHASE: START iteration 2: setInterval
1608448872313:INFO: TIMERS PHASE: Max interval count exceeded. Goodbye.
1608448872328:INFO: TIMERS PHASE: END iteration 2: setInterval

**Comment by jstevenperry** [comment]
Thanks for reporting this issue! Unfortunately I was unable to reproduce the issue you reported.

When running (using Node 10 per the setup instructions) the output I get matches the output from the Unit. This is from running on my machine (MacBook Pro 2014):

```
IX:Unit-5 sperry$ node --version
v10.23.1
IX:Unit-5 sperry$ node example6.js
1611286288782:INFO: MAINLINE: START
1611286288784:INFO: MAINLINE: END
1611286288785:INFO: MAINLINE MICROTASK: Promise.resolve.then
1611286288785:INFO: TIMERS PHASE: START iteration 0: setInterval
1611286288786:INFO: TIMERS PHASE: END iteration 0: setInterval
1611286288786:INFO: POLL PHASE: fs.readdir() callback: Directory contains: 8 files
1611286288786:INFO: POLL PHASE MICROTASK: setInterval.fs.readdir.Promise.resolve.then
1611286288787:INFO: CHECK PHASE: setInterval.setImmediate
1611286288787:INFO: CHECK PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
1611286288788:INFO: TIMERS PHASE: TIMER EXPIRED (from iteration 0): setInterval.setTimeout
1611286288788:INFO: TIMERS PHASE: START iteration 1: setInterval
1611286288789:INFO: TIMERS PHASE: END iteration 1: setInterval
1611286288789:INFO: TIMERS PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
1611286288789:INFO: POLL PHASE: fs.readdir() callback: Directory contains: 8 files
1611286288789:INFO: POLL PHASE MICROTASK: setInterval.fs.readdir.Promise.resolve.then
1611286288789:INFO: CHECK PHASE: setInterval.setImmediate
1611286288789:INFO: CHECK PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
1611286288790:INFO: TIMERS PHASE: TIMER EXPIRED (from iteration 1): setInterval.setTimeout
1611286288791:INFO: TIMERS PHASE: START iteration 2: setInterval
1611286288791:INFO: TIMERS PHASE: Max interval count exceeded. Goodbye.
1611286288791:INFO: TIMERS PHASE: END iteration 2: setInterval
1611286288791:INFO: TIMERS PHASE MICROTASK: setInterval.setTimeout.Promise.resolve.then
```

Notice I am using Node 10.23.1.

Please use Node 10 to run the examples in the unit and you shouldn't have any problems. Thanks for reading!

--jsp
