### ISSUE TITLE
load-db script gets stuck

### ISSUE THREAD

**Issue by mayankkamboj47** [jstevenperry/IBM-Developer#56]
When I run the "npm run load-db" command, I get the following output after which my terminal gets stuck. 

`1622538523852:INFO: mainline(): Script start at: 6/1/2021, 2:38:43 PM
1622538523856:INFO: Creating database file: ../data/shopping-list.db
1622538523857:INFO: createDbFixtures(): Dropping all tables...
1622538523860:INFO: createDbFixtures(): Dropping all tables, done.
1622538524285:INFO: createDbFixtures(): Creating item table...
1622538524286:INFO: createDbFixtures(): Creating item table, done.
1622538524763:INFO: createDbFixtures(): Creating brand table...
1622538524763:INFO: createDbFixtures(): Creating brand table, done.
1622538524765:INFO: createDbFixtures(): Creating shopping_list table...
1622538524765:INFO: createDbFixtures(): Creating shopping_list table, done.
1622538524767:INFO: createDbFixtures(): Creating shopping_list_item table...
1622538524767:INFO: createDbFixtures(): Creating shopping_list_item table, done.
1622538524768:INFO: createDbFixtures(): DONE
1622538524768:INFO: mainline:createDbFixtures(resolved Promise): Loading data for brand...
1622538524769:INFO: loadData(): Loading data files...
1622538524773:INFO: loadData():readableStream.on(open): Opened file: ../data/Grocery_Brands_Database.csv
`

**Comment by jstevenperry** [comment]
Please provide more details. What version of Node are you using for example.

**Comment by mayankkamboj47** [comment]
Node version is 14.17.0 and npm is 6.14.13.
